services:
  database:
    image: mysql:9.1.0
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Projeto-back-end/banco.sql:/docker-entrypoint-initdb.d/banco.sql:ro
    networks:
      - app-network

  backend:
    build:
      context: ./Projeto-back-end
      dockerfile: Dockerfile
    container_name: back_service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: cinema_db
      DB_USER: app
      DB_PASS: 123456
    depends_on:
      - database
    networks:
      - app-network
    restart: on-failure

  frontend:
    build:
      context: ./Projeto-front-end
      dockerfile: Dockerfile
    container_name: frontend-container
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    networks:
      - app-network
    restart: on-failure

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: on-failure

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge